### ISSUE TITLE
Python scripts issue

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/PiHomeHVAC#180]
error message produced by gateway.py when sensors comes online first time. 

```
Size of the String Received:  45
Date & Time:                  Mon Aug 30 23:43:17 2021
Full String Received:         20;255;0;0;17;2.3.2
Full Statement Received:      ['20', '255', '0', '0', '17', '2.3.2\n']
Node ID:                      20
Child Sensor ID:              255
Message Type:                 0
Acknowledge:                  0
Sub Type:                     17
Pay Load:                     2.3.2
1: Adding Node ID: 20 MySensors Version: 2.3.2
More info in log file: /var/www/logs/main.log
root@maxair:~#
````
/var/www/logs/main.log file contains following:

```
### 2021-08-30 23:43:17,960 - ERROR ###
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 238, in execute
    query = query % args
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/cron/gateway.py", line 417, in <module>
    0,
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 240, in execute
    self.errorhandler(self, ProgrammingError, str(m))
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 52, in defaulterrorhandler
    raise errorclass(errorvalue)
_mysql_exceptions.ProgrammingError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/cron/gateway.py", line 1032, in <module>
    print("DB Error %d: %s" % (e.args[0], e.args[1]))
IndexError: tuple index out of range
```
python3 /var/www/cron/find_mygw/find_mygw.py
find gateway goes through the ip address but unable to find gateway ip address.

**Comment by twa127** [comment]
Fix the bug when adding new sensor, tested okay now

**Comment by twa127** [comment]
I think this issue is now closed
